<a href="https://colab.research.google.com/github/randreove/03MAIR-Algoritmos_de_Optimizacion/blob/main/SEMINARIO/Rafael_Andreo-Seminario_Algoritmos.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Algoritmos de optimización - Seminario<br>
Nombre y Apellidos: Rafael Andreo de la Vega  <br>
Url: https://github.com/randreove/03MAIR-Algoritmos_de_Optimizacion/tree/main/SEMINARIO<br>
Problema:
> 1. Sesiones de doblaje <br>


Se precisa coordinar el doblaje de una película. Los actores del doblaje deben coincidir en las tomas en las que sus personajes aparecen juntos en las diferentes tomas. Los actores de doblaje cobran todos la misma cantidad por cada día que deben desplazarse hasta el estudio de grabación independientemente del número de tomas que se graben. No es posible grabar más de 6 tomas por día. El objetivo es planificar las sesiones por día de manera que el gasto por los servicios de los actores de doblaje sea el menor posible.







(*)¿Cuantas posibilidades hay sin tener en cuenta las restricciones?<br>



¿Cuantas posibilidades hay teniendo en cuenta todas las restricciones.




### Número de posibles soluciones sin ninguna restricción

Para calcular el número de posibles soluciones sin ninguna restricción en el problema debemos tener en cuenta que cada toma de doblaje puede asignarse a cualquier conjunto de actores, es decir, tenemos una elección independiente para cada toma.

Dado que tenemos 30 tomas de doblaje y 10 actores, el número total de posibles asignaciones es el producto de las opciones posibles para cada toma, es decir, 10 opciones para cada una de las 30 tomas.

El número total de posibles asignaciones sin restricciones es:

**Número total de asignaciones = 10^30**

### Número de posibles soluciones teniendo en cuenta las restricciones

Si los actores pueden repetirse en diferentes días pero las tomas no, entonces para calcular el número de posibles combinaciones de tomas para grabar en 5 días (ya que es lo óptimo), debemos considerar las siguientes situaciones:

* Día 1: 6 tomas
* Día 2: 6 tomas
* Día 3: 6 tomas
* Día 4: 6 tomas
* Día 5: 6 tomas

Para el Día 1, podemos elegir 6 tomas de las 30 disponibles. Para el Día 2, podemos elegir 6 tomas de las tomas restantes después de las seleccionadas en el Día 1 (es decir, 30 - 6 = 24). Continuamos este proceso para los Días 3, 4 y 5.

El número total de posibles combinaciones para grabar en 5 días sin repetir tomas es:

Número de combinaciones = 30 C 6 * 24 C 6 * 18 C 6 * 12 C 6 * 6 C 6

Donde 30 C 6 representa el número de combinaciones posibles de elegir 6 tomas de las 30 disponibles, y así sucesivamente.

Calculando este valor, obtenemos:

**Número de combinaciones = 593,775,905,560**

Este número es muchísimo más manejable que el número de soluciones posibles sin tener en cuenta las restricciones

Modelo para el espacio de soluciones<br>
(*) ¿Cual es la estructura de datos que mejor se adapta al problema? Argumentalo.(Es posible que hayas elegido una al principio y veas la necesidad de cambiar, arguentalo)


La estructura de datos que mejor se adapta al problema es la matriz. En ella he añadido los actores que participan en cada toma, indicando con un 1 si el actor participa en la toma y con un 0 si no participa. El número de filas será el número de tomas (30) y el número de columnas será el número de actores (10).

Es la mejor estructura ya que permite un acceso rápido y sencillo a los datos necesarios para el problema.

In [ ]:
# Datos del problema
actores_tomas_matrix = [
    [1,1,1,1,1,0,0,0,0,0],
    [0,0,1,1,1,0,0,0,0,0],
    [0,1,0,0,1,0,1,0,0,0],
    [1,1,0,0,0,0,1,1,0,0],
    [0,1,0,1,0,0,0,1,0,0],
    [1,1,0,1,1,0,0,0,0,0],
    [1,1,0,1,1,0,0,0,0,0],
    [1,1,0,0,0,1,0,0,0,0],
    [1,1,0,1,0,0,0,0,0,0],
    [1,1,0,0,0,1,0,0,1,0],
    [1,1,1,0,1,0,0,1,0,0],
    [1,1,1,1,0,1,0,0,0,0],
    [1,0,0,1,1,0,0,0,0,0],
    [1,0,1,0,0,1,0,0,0,0],
    [1,1,0,0,0,0,1,0,0,0],
    [0,0,0,1,0,0,0,0,0,1],
    [1,0,1,0,0,0,0,0,0,0],
    [0,0,1,0,0,1,0,0,0,0],
    [1,0,1,0,0,0,0,0,0,0],
    [1,0,1,1,1,0,0,0,0,0],
    [0,0,0,0,0,1,0,1,0,0],
    [1,1,1,1,0,0,0,0,0,0],
    [1,0,1,0,0,0,0,0,0,0],
    [0,0,1,0,0,1,0,0,0,0],
    [1,1,0,1,0,0,0,0,0,1],
    [1,0,1,0,1,0,0,0,1,0],
    [0,0,0,1,1,0,0,0,0,0],
    [1,0,0,1,0,0,0,0,0,0],
    [1,0,0,0,1,1,0,0,0,0],
    [1,0,0,1,0,0,0,0,0,0]
]

Según el modelo para el espacio de soluciones<br>
(*)¿Cual es la función objetivo?

(*)¿Es un problema de maximización o minimización?

La función objetivo del problema se podría definir como : <br> <br> Costo_Total = Σ (número de actores únicos en cada día de rodaje) <br> <br>

Como el coste de que un actor vaya a rodar un día es 1, el costo en un día será el número de actores que vayan a rodar. Por tanto, el costo total será el sumatorio de actores que van a rodar para cada día. Posteriormente sobre esa función objetivo se aplicarán ciertas restricciones.

Se trata de un problema de minimización, ya que el objetivo es que el costo sea lo más pequeño posible.

Diseña un algoritmo para resolver el problema por fuerza bruta

Respuesta

In [ ]:
import itertools

# Defino la función que realiza la búsqueda por fuerza bruta
def solve_doblaje_coordinacion_fuerza_bruta(actores_tomas_matrix, max_tomas_por_dia=6):
    n_actores, n_tomas = len(actores_tomas_matrix[0]), len(actores_tomas_matrix)
    mejores_asignaciones = None
    mejor_costo = float('inf')
    contador = 0

    # Generar todas las posibles permutaciones de asignaciones
    todas_asignaciones = itertools.permutations(range(n_tomas), n_actores)

    for asignaciones in todas_asignaciones:
        # Verificar que cada día no exceda el límite máximo de tomas por día
        tomas_por_dia = [0] * n_tomas
        actores_asignados = set()
        costo_actual = 0

        for actor, toma in enumerate(asignaciones):
            # Verificar que el actor no esté asignado a otra toma en el mismo día
            if tomas_por_dia[toma] == 0 and len(actores_asignados & set(actores_tomas_matrix[toma])) == 0:
                tomas_por_dia[toma] += 1
                actores_asignados |= set(actores_tomas_matrix[toma])
                costo_actual += 1

        if costo_actual < mejor_costo and all(tpd <= max_tomas_por_dia for tpd in tomas_por_dia):
            # Actualizar la mejor solución encontrada hasta el momento
            mejores_asignaciones = asignaciones
            mejor_costo = costo_actual
            contador = 1
        elif costo_actual == mejor_costo:
            contador += 1

    # Mostrar el resultado
    print("Planificación óptima encontrada mediante fuerza bruta:")
    for i, toma in enumerate(mejores_asignaciones):
        print(f"Día {i + 1}: Toma {toma + 1}")
    print(f"Gasto total: {mejor_costo}")
    print(f"Número de soluciones óptimas encontradas: {contador}")

# Datos del problema
actores_tomas_matrix = [
    # ... (datos del problema)
]



# Datos del problema
actores_tomas_matrix = [
    [1,1,1,1,1,0,0,0,0,0],
    [0,0,1,1,1,0,0,0,0,0],
    [0,1,0,0,1,0,1,0,0,0],
    [1,1,0,0,0,0,1,1,0,0],
    [0,1,0,1,0,0,0,1,0,0],
    [1,1,0,1,1,0,0,0,0,0],
    [1,1,0,1,1,0,0,0,0,0],
    [1,1,0,0,0,1,0,0,0,0],
    [1,1,0,1,0,0,0,0,0,0],
    [1,1,0,0,0,1,0,0,1,0],
    [1,1,1,0,1,0,0,1,0,0],
    [1,1,1,1,0,1,0,0,0,0],
    [1,0,0,1,1,0,0,0,0,0],
    [1,0,1,0,0,1,0,0,0,0],
    [1,1,0,0,0,0,1,0,0,0],
    [0,0,0,1,0,0,0,0,0,1],
    [1,0,1,0,0,0,0,0,0,0],
    [0,0,1,0,0,1,0,0,0,0],
    [1,0,1,0,0,0,0,0,0,0],
    [1,0,1,1,1,0,0,0,0,0],
    [0,0,0,0,0,1,0,1,0,0],
    [1,1,1,1,0,0,0,0,0,0],
    [1,0,1,0,0,0,0,0,0,0],
    [0,0,1,0,0,1,0,0,0,0],
    [1,1,0,1,0,0,0,0,0,1],
    [1,0,1,0,1,0,0,0,1,0],
    [0,0,0,1,1,0,0,0,0,0],
    [1,0,0,1,0,0,0,0,0,0],
    [1,0,0,0,1,1,0,0,0,0],
    [1,0,0,1,0,0,0,0,0,0]
]


# Resolver el problema de coordinación de doblaje mediante fuerza bruta
solve_doblaje_coordinacion_fuerza_bruta(actores_tomas_matrix)

Calcula la complejidad del algoritmo por fuerza bruta

La complejidad computacional del algoritmo puede analizarse por partes:

* **Generación de todas las posibles permutaciones:** El algoritmo utiliza la función itertools.permutations() para generar todas las posibles permutaciones de asignaciones de actores a tomas. La complejidad de generar todas las permutaciones de longitud n_actores de un conjunto de longitud n_tomas es O(n_tomas!).
* **Verificación de cada asignación:** Para cada permutación generada, el algoritmo realiza una verificación para asegurarse de que cada día no exceda el límite máximo de tomas por día. Esto implica recorrer las asignaciones y los actores asignados en cada iteración. La verificación implica un conjunto de operaciones para cada actor, lo que lleva a una complejidad de O(n_actores * n_tomas) por cada verificación de asignación.

Por tanto, la complejidad total del algoritmo es aproximadamente **O(n_tomas! * n_actores * n_tomas)**.

El algoritmo de fuerza bruta aquí presentado es exponencial y puede volverse impracticable para instancias grandes debido a la alta complejidad. En la práctica, se utilizan enfoques más eficientes, como algoritmos heurísticos y metaheurísticos, para abordar instancias más grandes del problema.

In [ ]:
import itertools

# Defino la función que realiza la búsqueda por fuerza bruta
def solve_doblaje_coordinacion_fuerza_bruta(actores_tomas_matrix, max_tomas_por_dia=6): # O(n_tomas! * n_actores * n_tomas).
    n_actores, n_tomas = len(actores_tomas_matrix[0]), len(actores_tomas_matrix)
    mejores_asignaciones = None
    mejor_costo = float('inf')
    contador = 0

    # Generar todas las posibles permutaciones de asignaciones
    todas_asignaciones = itertools.permutations(range(n_tomas), n_actores) # O(n_tomas!)


    for asignaciones in todas_asignaciones:
        # Verificar que cada día no exceda el límite máximo de tomas por día
        tomas_por_dia = [0] * n_tomas
        actores_asignados = set()
        costo_actual = 0

        for actor, toma in enumerate(asignaciones): # O(n_actores * n_tomas)
            # Verificar que el actor no esté asignado a otra toma en el mismo día
            if tomas_por_dia[toma] == 0 and len(actores_asignados & set(actores_tomas_matrix[toma])) == 0:
                tomas_por_dia[toma] += 1
                actores_asignados |= set(actores_tomas_matrix[toma])
                costo_actual += 1

        if costo_actual < mejor_costo and all(tpd <= max_tomas_por_dia for tpd in tomas_por_dia):
            # Actualizar la mejor solución encontrada hasta el momento
            mejores_asignaciones = asignaciones
            mejor_costo = costo_actual
            contador = 1
        elif costo_actual == mejor_costo:
            contador += 1

    # Mostrar el resultado
    print("Planificación óptima encontrada mediante fuerza bruta:")
    for i, toma in enumerate(mejores_asignaciones):
        print(f"Día {i + 1}: Toma {toma + 1}")
    print(f"Gasto total: {mejor_costo}")
    print(f"Número de soluciones óptimas encontradas: {contador}")

# Datos del problema
actores_tomas_matrix = [
    # ... (datos del problema)
]

# Resolver el problema de coordinación de doblaje mediante fuerza bruta
solve_doblaje_coordinacion_fuerza_bruta(actores_tomas_matrix)


(*)Diseña un algoritmo que mejore la complejidad del algortimo por fuerza bruta. Argumenta porque crees que mejora el algoritmo por fuerza bruta

He diseñado un algoritmo que resuelve el problema mediante GRASP. Mejora la complejidad del algoritmo por fuerza bruta ya que parte de una solución inicial estimada y va optimizando sobre ella hasta llegar a una solución óptima (que no la solución más óptima). Al no buscar todas las soluciones, reduce en gran medida la complejidad.

Para un problema con tantas soluciones como el que trabajamos, buscar todas las posibles soluciones puede ser muy ineficiente conputacionalmente. Por tanto, al aplicar una metaheurística logramos disminuir la complejidad del algoritmo y obtener una solución óptima en un tiempo razonable.

In [ ]:
import random

# Defino una variable que utilizaré más adelante
contador = 0

# Defino la funcion que construira la solucion inicial
def construir_solucion_inicial(actores_tomas_matrix, max_tomas_por_dia):
    n_actores, n_tomas = len(actores_tomas_matrix[0]), len(actores_tomas_matrix)
    tomas_restantes = set(range(n_tomas))
    solucion = []

    while tomas_restantes:
        actor_disponible = list(range(n_actores))
        random.shuffle(actor_disponible)
        tomas_dia_actual = []

        for actor in actor_disponible:
            tomas_candidatas = [toma for toma in tomas_restantes if actores_tomas_matrix[toma][actor]]
            random.shuffle(tomas_candidatas)
            tomas_dia_actual.extend(tomas_candidatas[:max_tomas_por_dia - len(tomas_dia_actual)])

            if len(tomas_dia_actual) >= max_tomas_por_dia:
                break

        solucion.append(tomas_dia_actual)
        tomas_restantes.difference_update(set(tomas_dia_actual))

    return solucion

# Defino la funcion que me calcula el costo total
def costo_total(solucion_actual, actores_tomas_matrix):
    n_actores = len(actores_tomas_matrix[0])
    costo_total = 0

    for dia_tomas in solucion_actual:
        actores_dia = set()
        for toma in dia_tomas:
            actores_dia.update({actor for actor in range(n_actores) if actores_tomas_matrix[toma][actor]})

        costo_total += len(actores_dia)

    return costo_total

# Defino la funcion que me optimiza mediante grasp el problema
def solve_doblaje_coordinacion_grasp(actores_tomas_matrix, max_tomas_por_dia=6, max_iter=100000):
    mejor_solucion = None
    mejor_costo = float('inf')

    for _ in range(max_iter):
        solucion_actual = construir_solucion_inicial(actores_tomas_matrix, max_tomas_por_dia)
        costo_actual = costo_total(solucion_actual, actores_tomas_matrix)

        if costo_actual < mejor_costo:
            mejor_solucion = solucion_actual
            mejor_costo = costo_actual
            contador=1
        elif costo_actual == mejor_costo:
            contador+=1

    # Mostrar el resultado
    print(f"Planificación óptima encontrada en {max_iter} iteraciones:")
    for i, dia_tomas in enumerate(mejor_solucion):
        print(f"Día {i + 1}: ", end="")
        for toma in dia_tomas:
            print(f"Toma {toma + 1}", end=" ")
        print()
    print(f"Gasto total: {mejor_costo}")
    print(f"Número de soluciones óptimas encontradas: {contador}")

# Datos del problema
actores_tomas_matrix = [
    [1,1,1,1,1,0,0,0,0,0],
    [0,0,1,1,1,0,0,0,0,0],
    [0,1,0,0,1,0,1,0,0,0],
    [1,1,0,0,0,0,1,1,0,0],
    [0,1,0,1,0,0,0,1,0,0],
    [1,1,0,1,1,0,0,0,0,0],
    [1,1,0,1,1,0,0,0,0,0],
    [1,1,0,0,0,1,0,0,0,0],
    [1,1,0,1,0,0,0,0,0,0],
    [1,1,0,0,0,1,0,0,1,0],
    [1,1,1,0,1,0,0,1,0,0],
    [1,1,1,1,0,1,0,0,0,0],
    [1,0,0,1,1,0,0,0,0,0],
    [1,0,1,0,0,1,0,0,0,0],
    [1,1,0,0,0,0,1,0,0,0],
    [0,0,0,1,0,0,0,0,0,1],
    [1,0,1,0,0,0,0,0,0,0],
    [0,0,1,0,0,1,0,0,0,0],
    [1,0,1,0,0,0,0,0,0,0],
    [1,0,1,1,1,0,0,0,0,0],
    [0,0,0,0,0,1,0,1,0,0],
    [1,1,1,1,0,0,0,0,0,0],
    [1,0,1,0,0,0,0,0,0,0],
    [0,0,1,0,0,1,0,0,0,0],
    [1,1,0,1,0,0,0,0,0,1],
    [1,0,1,0,1,0,0,0,1,0],
    [0,0,0,1,1,0,0,0,0,0],
    [1,0,0,1,0,0,0,0,0,0],
    [1,0,0,0,1,1,0,0,0,0],
    [1,0,0,1,0,0,0,0,0,0]
]

# Resolver el problema de coordinación de doblaje con GRASP
solve_doblaje_coordinacion_grasp(actores_tomas_matrix)


(*)Calcula la complejidad del algoritmo

Para analizar la coplejidad del algoritmo vamos a analizar las funciones del mismo:

*   Función construir_solucion_inicial:
  * El bucle while *tomas_restantes* se ejecuta en función del número de tomas restantes en cada iteración. En el peor caso, este bucle se ejecutará **n_tomas** veces.
  * Dentro del bucle, el bucle *for actor in actor_disponible* itera sobre todos los actores disponibles. En el peor caso, este bucle se ejecutará **n_actores** veces.
  * Dentro del bucle *for actor in actor_disponible*, la clist comprehension *tomas_candidatas* crea una lista con todas las tomas candidatas en función de los actores disponibles. En el peor caso, esto puede tomar **n_tomas** operaciones, aunque es probable que sea mucho menos en la mayoría de los casos.
  * En general, la función construir_solucion_inicial tiene una complejidad aproximada de **O(n_tomas * n_actores)**.

*   Función costo_total:
  * El bucle *for dia_tomas in solucion_actual* itera sobre todos los días de rodaje en la solución actual. En el peor caso, este bucle se ejecutará **n_tomas** veces.
  * El bucle *for toma in dia_tomas* itera sobre el número de tomas que hay en cada día. En el peor caso, este bucle se ejecutará **max_tomas_por_dia** veces (que a nivel práctico son 6).
  * Dentro del bucle *for dia_tomas in solucion_actual*, la set comprehension *actores_dia* crea un conjunto con todos los actores únicos que participan en las tomas de ese día. En el peor caso, esto tomará **n_actores** operaciones para cada día.
  * En general, la función costo_total tiene una complejidad aproximada de **O(n_tomas * max_tomas_por_dia * n_actores)**.

* Función solve_doblaje_coordinacion_grasp:
  * El bucle *for _ in range(max_iter)* se ejecutará **max_iter** veces, que es una constante proporcionada por el usuario.
  * En cada iteración, se llama a la función *construir_solucion_inicial* y *costo_total*, que ya hemos analizado con complejidad **O(n_tomas * n_actores)** y **O(n_tomas * max_tomas_por_dia * n_actores)**, respectivamente.
  * En general, la función solve_doblaje_coordinacion_grasp tiene una complejidad aproximada de **O(max_iter * n_tomas * max_tomas_por_dia * n_actores)**.

No he contabilizado la complejidad de la parte en la que imprimo los resultados por la pantalla ya que no se trata propiamente del algoritmo, sino que es una utilidad que usamos para mostrar gráficamente los resultados, pero que no es fundamental.

In [ ]:
def construir_solucion_inicial(actores_tomas_matrix, max_tomas_por_dia): # O(n_actores*n_tomas)
    n_actores, n_tomas = len(actores_tomas_matrix[0]), len(actores_tomas_matrix)
    tomas_restantes = set(range(n_tomas))
    solucion = []

    while tomas_restantes: # n_tomas
        actor_disponible = list(range(n_actores))
        random.shuffle(actor_disponible)
        tomas_dia_actual = []

        for actor in actor_disponible: # n_actores
            tomas_candidatas = [toma for toma in tomas_restantes if actores_tomas_matrix[toma][actor]] # n_tomas
            random.shuffle(tomas_candidatas)
            tomas_dia_actual.extend(tomas_candidatas[:max_tomas_por_dia - len(tomas_dia_actual)])

            if len(tomas_dia_actual) >= max_tomas_por_dia:
                break

        solucion.append(tomas_dia_actual)
        tomas_restantes.difference_update(set(tomas_dia_actual))

    return solucion

def costo_total(solucion_actual, actores_tomas_matrix): # O(n_tomas*max_tomas_por_dia*n_actores)
    n_actores = len(actores_tomas_matrix[0])
    costo_total = 0

    for dia_tomas in solucion_actual: #n_tomas
        actores_dia = set()
        for toma in dia_tomas: # max_tomas_por_dia
            actores_dia.update({actor for actor in range(n_actores) if actores_tomas_matrix[toma][actor]}) # n_actores

        costo_total += len(actores_dia)

    return costo_total

def solve_doblaje_coordinacion_grasp(actores_tomas_matrix, max_tomas_por_dia=6, max_iter=100000): # O(max_iter*n_tomas*max_tomas_por_dia*n_actores)
    mejor_solucion = None
    mejor_costo = float('inf')

    for _ in range(max_iter): #max_iter
        solucion_actual = construir_solucion_inicial(actores_tomas_matrix, max_tomas_por_dia) # O(n_actores*n_tomas)
        costo_actual = costo_total(solucion_actual,actores_tomas_matrix) # O(n_tomas*max_tomas_por_dia*n_actores)

        if costo_actual < mejor_costo:
            mejor_solucion = solucion_actual
            mejor_costo = costo_actual
            contador=1
        elif costo_actual == mejor_costo:
            contador+=1

    # Mostrar el resultado
    print(f"Planificación óptima encontrada en {max_iter} iteraciones:")
    for i, dia_tomas in enumerate(mejor_solucion):
        print(f"Día {i + 1}: ", end="")
        for toma in dia_tomas:
            print(f"Toma {toma + 1}", end=" ")
        print()
    print(f"Gasto total: {mejor_costo}")
    print(f"Número de soluciones óptimas encontradas: {contador}")

Según el problema (y tenga sentido), diseña un juego de datos de entrada aleatorios

Respuesta

In [1]:
import numpy as np

# Tamaño de la matriz
filas = 30
columnas = 10

# Generar una matriz aleatoria de 0 y 1
actores_tomas_matrix = np.random.randint(2, size=(filas, columnas))

print(actores_tomas_matrix)


[[0 0 1 0 0 0 1 0 1 1]
 [0 1 1 1 1 1 0 0 1 0]
 [0 0 1 1 0 0 1 0 0 1]
 [1 0 1 0 0 1 0 1 0 1]
 [1 1 1 1 1 1 0 0 0 0]
 [1 0 0 1 1 1 1 0 0 0]
 [1 0 1 0 0 1 0 1 1 1]
 [0 0 0 0 1 1 1 0 0 1]
 [0 0 1 1 0 0 1 0 0 0]
 [0 0 1 1 0 1 1 1 1 1]
 [0 0 0 1 0 0 1 0 0 0]
 [0 1 0 1 1 0 1 0 1 0]
 [1 1 0 0 1 1 1 1 1 0]
 [1 0 0 0 1 1 1 0 1 1]
 [0 0 0 1 0 0 0 0 0 1]
 [1 0 1 0 1 1 1 0 0 1]
 [1 0 1 1 1 0 1 0 1 1]
 [0 1 0 0 1 0 0 1 1 1]
 [0 1 0 0 0 0 0 1 0 0]
 [0 1 0 1 1 1 1 0 1 0]
 [0 0 1 1 0 0 1 1 0 1]
 [1 0 1 1 1 1 1 0 0 1]
 [1 0 1 1 1 0 0 0 0 1]
 [0 1 0 1 1 1 1 1 0 0]
 [0 1 0 1 0 1 0 0 0 1]
 [1 0 1 1 1 0 1 1 0 0]
 [1 1 0 0 0 1 0 1 0 1]
 [0 0 1 1 0 0 0 0 0 0]
 [0 0 0 1 1 0 1 0 1 0]
 [0 1 1 1 0 0 0 1 0 0]]


Aplica el algoritmo al juego de datos generado

Respuesta

In [3]:
import random

# Defino una variable que utilizaré más adelante
contador = 0

# Defino la funcion que construira la solucion inicial
def construir_solucion_inicial(actores_tomas_matrix, max_tomas_por_dia):
    n_actores, n_tomas = len(actores_tomas_matrix[0]), len(actores_tomas_matrix)
    tomas_restantes = set(range(n_tomas))
    solucion = []

    while tomas_restantes:
        actor_disponible = list(range(n_actores))
        random.shuffle(actor_disponible)
        tomas_dia_actual = []

        for actor in actor_disponible:
            tomas_candidatas = [toma for toma in tomas_restantes if actores_tomas_matrix[toma][actor]]
            random.shuffle(tomas_candidatas)
            tomas_dia_actual.extend(tomas_candidatas[:max_tomas_por_dia - len(tomas_dia_actual)])

            if len(tomas_dia_actual) >= max_tomas_por_dia:
                break

        solucion.append(tomas_dia_actual)
        tomas_restantes.difference_update(set(tomas_dia_actual))

    return solucion

# Defino la funcion que me calcula el costo total
def costo_total(solucion_actual, actores_tomas_matrix):
    n_actores = len(actores_tomas_matrix[0])
    costo_total = 0

    for dia_tomas in solucion_actual:
        actores_dia = set()
        for toma in dia_tomas:
            actores_dia.update({actor for actor in range(n_actores) if actores_tomas_matrix[toma][actor]})

        costo_total += len(actores_dia)

    return costo_total

# Defino la funcion que me optimiza mediante grasp el problema
def solve_doblaje_coordinacion_grasp(actores_tomas_matrix, max_tomas_por_dia=6, max_iter=100000):
    mejor_solucion = None
    mejor_costo = float('inf')

    for _ in range(max_iter):
        solucion_actual = construir_solucion_inicial(actores_tomas_matrix, max_tomas_por_dia)
        costo_actual = costo_total(solucion_actual, actores_tomas_matrix)

        if costo_actual < mejor_costo:
            mejor_solucion = solucion_actual
            mejor_costo = costo_actual
            contador=1
        elif costo_actual == mejor_costo:
            contador+=1

    # Mostrar el resultado
    print(f"Planificación óptima encontrada en {max_iter} iteraciones:")
    for i, dia_tomas in enumerate(mejor_solucion):
        print(f"Día {i + 1}: ", end="")
        for toma in dia_tomas:
            print(f"Toma {toma + 1}", end=" ")
        print()
    print(f"Gasto total: {mejor_costo}")
    print(f"Número de soluciones óptimas encontradas: {contador}")

# Resolver el problema de coordinación de doblaje con GRASP
solve_doblaje_coordinacion_grasp(actores_tomas_matrix)


Planificación óptima encontrada en 100000 iteraciones:
Día 1: Toma 12 Toma 13 Toma 2 Toma 20 Toma 18 Toma 7 
Día 2: Toma 30 Toma 19 Toma 24 Toma 5 Toma 27 Toma 25 
Día 3: Toma 10 Toma 17 Toma 1 Toma 29 Toma 14 Toma 4 
Día 4: Toma 16 Toma 23 Toma 26 Toma 8 Toma 22 Toma 6 
Día 5: Toma 28 Toma 3 Toma 9 Toma 21 Toma 15 Toma 11 
Gasto total: 41
Número de soluciones óptimas encontradas: 3


Enumera las referencias que has utilizado(si ha sido necesario) para llevar a cabo el trabajo

Respuesta

Describe brevemente las lineas de como crees que es posible avanzar en el estudio del problema. Ten en cuenta incluso posibles variaciones del problema y/o variaciones al alza del tamaño

Respuesta